### ISSUE TITLE
Problem with NodeTrix recently

### ISSUE THREAD

**Issue by mpeeples2008** [IRT-SystemX/nodetrix#1]
I have used your nodetrix code for a while both locally on my computer using a Python simple server and on a web server. It has always worked with no problems through at least November of last year. I just tried to run a file set up I had previously used and never got past the spinning wheel when loading. I'm guessing some remote dependency changed or something but I don't know enough about js to sort this out. I'm happy to help troubleshoot and will continue working on my end but wondered if you had seen anything similar (though this project may just be outdated).

**Comment by nheulot** [comment]
Thanks for opening this issue. We did not use this code lately. Some urls were broken. They were pointing to external dependencies. We just pushed a new version on master without urls but with local files. Does it work for you now ?

**Comment by mpeeples2008** [comment]
Thank you so much for updating the code. I've found this application very useful and I appreciate you keeping up with it years after the fact. Updating the external dependencies got it working. Everything is back to normal with one small exception. For whatever reason whenever I generate matrices it seems continue row colors off past the frame. It's usable in this format but just a little different than the previous behavior. This could be  a problem on my end as I'm working with a slightly modified html file based on your example.

Thanks again for your help.

![nodetrix_screenshot](https://user-images.githubusercontent.com/36179457/171233631-81f6719d-dffa-451c-a459-74ef7c15c05e.jpg)
