### ISSUE TITLE
The matrix shows the problem

### ISSUE THREAD

**Issue by caoyang12** [IRT-SystemX/nodetrix#2]
<img width="926" alt="截屏2024-10-23 21 22 57" src="https://github.com/user-attachments/assets/137b3b7c-c11f-42b1-ac42-ec3ac0441759">
Why is there a column in the matrix I generated?

**Comment by caoyang12** [comment]
Why is one of the columns in the matrix layout I generated too long?

**Comment by nheulot** [comment]
Thanks for your comment. It seems that the behaviour of the CSS library changed recently. I just pushed a commit to avoid the CSS conflict. The matrix rendering should be fixed.

**Comment by caoyang12** [comment]
Thank you very much for your help. I've implemented the changes you suggested, and the matrix rendering is now working as expected. Your guidance was invaluable.
